<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
</button>')
    ->setMessageCloseString('</div>');

echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('warning', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));

?>
<div class="page-header">
<h1>Mannschaften</h1>
</div>

<?php if (count($mannschaften) != 0) { ?>

<table class="table table-hover table-bordered ">
    <thead>
    <tr class="success">
        <th>Name</th>
        <th>Kuerzel</th>
        <th>Gruppe</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->mannschaften as $m) : ?>
        <tr>
            <td><?php echo $m->getName();?></td>
            <td><?php echo $m->getKuerzel();?></td>
            <td><?php echo $m->getGruppe();?></td>
           
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php } else {
    echo 'Noch keine Mannschaften vorhanden';
}?>
