<h1>Mannschaft</h1>

<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Kuerzel</th>
        <th>Gruppe</th>
        <th></th>
        
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->mannschaften as $m) : ?>
        <tr>
            <td><?php echo $m->getM_id();?></td>
            <td><?php echo $m->getName();?></td>
            <td><?php echo $m->getKuerzel();?></td>
            <td><?php echo $m->getGruppe();?></td>
            <td>   </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
