<h1>Albums</h1>


<!--<?php foreach ($message as $m) : ?>
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Success!</strong> <?php echo $m?>
    </div>
<?php endforeach; ?>-->

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
</button>')
    ->setMessageCloseString('</div>');

echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('warning', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));

?>


<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Artist</th>
        <th>Title</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->albums as $a) : ?>
        <tr>
            <td><?php echo $a->getId();?></td>
            <td><?php echo $a->getArtist();?></td>
            <td><?php echo $a->getTitle();?></td>
            <td>
                <a href="<?php echo $this->url('album2/edit', array('id' => $a->getId())); ?>">Edit</a>
                <a href="<?php echo $this->url('album2/delete', array('id' => $a->getId())); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
