<h1>Albums</h1>

<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Artist</th>
        <th>Title</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->albums as $a) : ?>
        <tr>
            <td><?php echo $a->getId();?></td>
            <td><?php echo $a->getArtist();?></td>
            <td><?php echo $a->getTitle();?></td>
            <td>
                <a href="<?php echo $this->url('album2/edit', array('id' => $a->getId())); ?>">Edit</a>
                <a href="<?php echo $this->url('album2/delete', array('id' => $a->getId())); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
