<div class="page-header">
<h1>Neuen Beitrag verfassen</h1>
</div>
<?php

$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('post/add', array(), true));
$form->prepare();

$form->get('submit')->setValue('Beitrag erstellen');
$form->get('submit')->setAttribute('class', 'btn btn-success');




echo $this->form()->openTag($form);


echo $this->formHidden($form->get('post-fieldset')->get('p_id'));
echo $this->formHidden($form->get('post-fieldset')->get('b_id')->setValue($this->zfcUserIdentity()->getId()));
echo $this->formHidden($form->get('post-fieldset')->get('g_id'));
?>

<div style="width: 800px;" class="form-group">

    <?php
    $form->get('post-fieldset')->get('betreff')->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', $form->get('post-fieldset')->get('betreff')->getLabel());

    echo $this->formElement($form->get('post-fieldset')->get('betreff'));
    ?>

</div>

<div style="width: 800px;" class="form-group">

    <?php
    $form->get('post-fieldset')->get('text')->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', $form->get('post-fieldset')->get('text')->getLabel());

    echo $this->formElement($form->get('post-fieldset')->get('text'));
    ?>

</div>

    <?php
  

    echo $this->formSubmit($form->get('submit'));

#Statt der Zeile:
#echo $this->formCollection($form);

echo $this->form()->closeTag();

