<h1>Neuen Beitrag verfassen</h1>
<?php

$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('post/add', array(), true));
$form->prepare();

$form->get('submit')->setValue('Beitrag erstellen');

echo $this->form()->openTag($form);

#Die paar Zeilen:
echo $this->formHidden($form->get('post-fieldset')->get('p_id'));
#setValue setzt das was in dem Feld schon von vornherein drinstehen soll. Hier nur beispielhaft mit der Mail.
#die UserId sollte natürlich ein hidden field sein (wie die erste Zeile) und das wird dann halt befüllt.
echo $this->formHidden($form->get('post-fieldset')->get('b_id')->setValue($this->zfcUserIdentity()->getId()));
echo $this->formHidden($form->get('post-fieldset')->get('g_id'));
echo $this->formRow($form->get('post-fieldset')->get('betreff'));
echo $this->formRow($form->get('post-fieldset')->get('text'));

echo $this->formSubmit($form->get('submit'));

#Statt der Zeile:
#echo $this->formCollection($form);

echo $this->form()->closeTag();