<h1>Neues Spiel hinzufuegen</h1>
<?php
$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url());
$form->prepare();

$form->get('submit')->setValue('Spiel anlegen');
$form->get('submit')->setAttribute('class', 'btn btn-success');

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('spiel-fieldset')->get('s_id'));
?>

<?php foreach ($form->get('spiel-fieldset') as $element) : ?>

    <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <?php
        if ('submit' != $element->getAttribute('type')) { ?>
            <label class="control-label"><?php echo $element->getLabel() ?></label>
            <?php
            $element->setAttribute('class', 'form-control')
                ->setAttribute('placeholder', $element->getLabel());
        } else {
            $element->setAttribute('class', 'btn btn-success');
        }
        if ($element instanceof Zend\Form\Element\Captcha) {
            echo $this->formCaptcha($element);
        } else {
            echo $this->formElement($element);
        }
        if ($this->formElementErrors($element)) : ?>
            <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<p class="help-block">')
                ->setMessageSeparatorString('</p><p class="help-block">')
                ->setMessageCloseString('</p>')
                ->render($element);
            ?>
        <?php endif; ?>
    </div>

    <?php
endforeach;

echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
