<div class="page-header">
<h1>&Uumlbersicht &uumlber Ihre Tippgemeinschaften</h1>
</div>

<!--<?php foreach ($message as $m) : ?>
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Success!</strong> <?php echo $m?>
    </div>
<?php endforeach; ?>-->

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>')
    ->setMessageCloseString('</div>');

echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));

?>


<table class="table table-hover">

    <thead>
    <tr class="success">
        
        <th>Name der Tippgemeinschaft</th>
        <th>Beschreibung der Tippgemeinschaft</th>
        <th></th>
        
    </tr >
    </thead>
    <tbody>
    <?php foreach($this->gruppen as $g) : ?>
        <tr >
           
            <td ><?php echo $g->getName();?></td>
            <td><?php echo $g->getBeschreibung();?></td>
           
             <td>
             <input type="button" class="btn btn-success" onclick="location.href='<?php echo $this->url('gruppe/detail', array('g_id' => $g->getG_id())); ?>';" value="Detailansicht" />
 				
            </td>
           

        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
