
<h1>Tippgemeinschaft verlassen</h1>
<p>
    Sind Sie sicher, dass Sie aus der Tippgemeinschaft
    '<?php echo $this->escapeHtml($this->gruppe->getName()); ?>'
   austreten wollen?
</p>
<form action="<?php echo $this->url('gruppe/delete', array(), true) ?>" method="post">

 			
    <input type="submit" class="btn btn-success" name="delete_confirmation" value="ja" />
    <input type="submit" class="btn btn-danger" name="delete_confirmation" value="nein" />
</form>