<?php if ($message == 1) { ?>
    <div class="alert alert-dismissible alert-info">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
            &times;
        </button>Turnier hat schon begonnen. Zusatztipp-Abgabe nicht mehr moeglich</div>
<?php
}
?>

<div class="page-header">
<h1>Zusatztipp abgeben</h1>
</div>


<?php

$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('tipp/addzusatz', array(), true));
$form->prepare();

$form->get('submit')->setValue('Zusatztipp abgeben');
$form->get('submit')->setAttribute('class', 'btn btn-success');

echo $this->form()->openTag($form);
?>

<?php foreach ($form as $element) : ?>

    <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <?php
        if ('submit' != $element->getAttribute('type')) { ?>
            <label class="control-label"><?php echo $element->getLabel() ?></label>
            <?php
            $element->setAttribute('class', 'form-control')
                ->setAttribute('placeholder', $element->getLabel());
        } else {
            $element->setAttribute('class', 'btn btn-success');
        }
        if ($element instanceof Zend\Form\Element\Captcha) {
            echo $this->formCaptcha($element);
        } else {
            echo $this->formElement($element);
        }
        if ($this->formElementErrors($element)) : ?>
            <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<p class="help-block">')
                ->setMessageSeparatorString('</p><p class="help-block">')
                ->setMessageCloseString('</p>')
                ->render($element);
            ?>
        <?php endif; ?>
    </div>

    <?php
endforeach;

echo $this->form()->closeTag();
