<h1>Tipp zu folgendem Spiel abgeben:</h1>

<table class="table">
    <tr>
        <th>Erste Mannschaft</th>
        <th>Zweite Mannschaft</th>
    </tr>
    <tr>
        <td>
       <?php echo $mannschaft1['name']?> 
     
        </td>
        <td>
        <?php echo $mannschaft2['name']?> 
        </td>
    </tr>
</table>

<?php
$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('tipp/add', array(), true));
$form->prepare();

$form->get('submit')->setValue('Tipp abgeben');

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('tipp-fieldset')->get('t_id'));
echo $this->formHidden($form->get('tipp-fieldset')->get('b_id')->setValue($this->zfcUserIdentity()->getId()));

echo $this->formRow($form->get('tipp-fieldset')->get('tipp1'));
echo $this->formRow($form->get('tipp-fieldset')->get('tipp2'));
echo $this->formSubmit($form->get('submit'));

#Statt der Zeile:
#echo $this->formCollection($form);

echo $this->form()->closeTag();