<h1>Zusatztipps aktualisieren</h1>
<?php

$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('tipp/update', array(), true));
$form->prepare();

$form->get('submit')->setValue('Aktualisieren');
$form->get('submit')->setAttribute('class', 'btn btn-success');

echo $this->form()->openTag($form);

//echo $this->formCollection($form);
?>

<div style="width: 330px;">
    <?php foreach ($form as $element) : ?>

            <?php
            if ('submit' != $element->getAttribute('type')) { ?>
                <label class="control-label"><?php echo $element->getLabel() ?></label>
                <div class="input-group">
                    <?php echo $this->formElement($element); ?>
                </div>
                <?php
            } else {
                $element->setAttribute('class', 'btn btn-success');
                echo $this->formElement($element);
            }
            if ($this->formElementErrors($element)) : ?>
                <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<p class="help-block">')
                    ->setMessageSeparatorString('</p><p class="help-block">')
                    ->setMessageCloseString('</p>')
                    ->render($element);
                ?>
            <?php endif; ?>

        <?php
    endforeach;
    ?>
</div>

<?php
echo $this->form()->closeTag();
?>