<h1>Details zum Tipp</h1>

<table class="table">
    <thead>
    <tr>
        <th>s_id</th>
        <th>Erste Mannschaft</th>
        <th>Tipp Anzahl der Tore</th>
        <th>Zweite Mannschaft </th>
         <th>Tipp Anzahl der Tore</th>
         <th></th>
         
         
        
    </tr>
    </thead>
    <tbody>
      
        <tr>
     <td> <?php echo $tipp->getS_id()?> </td>
  	 <td> <?php echo $mannschaft1['name']?> </td>
     <td> <?php echo $tipp->getTipp1()?> </td>
     <td> <?php echo $mannschaft2['name']?> </td>
     <td> <?php echo $tipp->getTipp2()?> </td>
      <td><input type="button" class="btn btn-success" onclick="location.href='<?php echo $this->url('tipp/edit', array('t_id' => $tipp->getT_id())); ?>'"  value="Bearbeiten" /></td>
 			
   
             
           
           
        </tr>
 
    

    </tbody>
</table>
