<h1>Tipps</h1>

<table class="table">
    <thead>
    <tr>
        <th>s_id</th>
        <th>Erste Mannschaft</th>
        <th>Tipp Anzahl der Tore</th>
        <th>Zweite Mannschaft </th>
         <th>Tipp Anzahl der Tore</th>
         <th>Punkte</th>
        
    </tr>
    </thead>
    <tbody>
        <?php foreach($this->tipps as $t) : ?>
        <tr>
            <td><?php echo $t['s_id']; ?></td>
            <td><?php echo $t['mannschaft1'];?></td>
            <td><?php echo $t['tipp1'];?></td>
            <td><?php echo $t['mannschaft2'];?></td>
            <td><?php echo $t['tipp2'];?></td>
            <td><?php echo $t['punkte'];?></td>
            
             
           
           
        </tr>
    <?php endforeach; ?>
    

    </tbody>
</table>
